# Generated by Django 4.0.1 on 2022-01-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0002_alter_student_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='completed_units',
            field=models.ManyToManyField(related_name='completed_units', to='app_uniplan.Unit'),
        ),
    ]
