# Generated by Django 4.0.1 on 2022-01-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0003_student_profile_completed_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unitguideURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
