# Generated by Django 4.0.1 on 2022-01-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0004_alter_unit_description_alter_unit_unitguideurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='completed_units',
        ),
        migrations.AddField(
            model_name='enrollments',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.semester'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='enrollments',
            field=models.ManyToManyField(to='app_uniplan.Enrollments'),
        ),
    ]
