# Generated by Django 4.0.1 on 2022-01-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0005_remove_student_profile_completed_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='enrollments',
        ),
    ]
