# Generated by Django 4.0.1 on 2022-01-20 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_uniplan', '0006_remove_student_profile_enrollments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.course'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
