# Generated by Django 4.0.1 on 2022-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0010_alter_assignment_total_marks_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='marks',
            field=models.IntegerField(blank=True, help_text='The marks received for the assignment', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('graded', 'Graded')], default='open', max_length=10, null=True),
        ),
    ]
