# Generated by Django 4.0.1 on 2022-01-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0011_assignment_marks_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='The due date of the assignment', null=True),
        ),
    ]
