# Generated by Django 4.0.1 on 2022-01-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0013_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
