# Generated by Django 4.0.1 on 2022-01-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0014_alter_unit_unit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.course')),
            ],
        ),
        migrations.CreateModel(
            name='MajorSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the major sequence', max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.course')),
            ],
        ),
        migrations.CreateModel(
            name='MinorSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the minor sequence', max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.course')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.coresequence')),
                ('major_sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.majorsequence')),
                ('minor_sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.minorsequence')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.unit')),
            ],
        ),
    ]
