# Generated by Django 4.0.1 on 2022-01-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0015_coresequence_majorsequence_minorsequence_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SequenceUnits',
            new_name='UnitSet',
        ),
    ]
