# Generated by Django 4.0.1 on 2022-01-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0016_rename_sequenceunits_unitset'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorsequence',
            name='units',
            field=models.ManyToManyField(to='app_uniplan.Unit'),
        ),
    ]
