# Generated by Django 4.0.1 on 2022-01-30 00:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_uniplan', '0018_unitset_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)])),
                ('credit_points', models.FloatField(default=0)),
                ('eftsl_value', models.FloatField(default=0)),
                ('incompatible_units_text', models.TextField(blank=True, null=True)),
                ('prerequisite_units_text', models.TextField(blank=True, null=True)),
                ('corequisite_units_text', models.TextField(blank=True, null=True)),
                ('assignments_json', models.JSONField(blank=True, null=True)),
                ('hurdle_text', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trimester_availability', models.ManyToManyField(blank=True, to='app_uniplan.Semester')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.unit')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='unit_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.unitdata'),
        ),
    ]
