# Generated by Django 4.0.1 on 2022-02-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0019_unitdata_assignment_unit_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uniplan.majorsequence'),
        ),
        migrations.AddField(
            model_name='unitdata',
            name='unitguide_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
