# Generated by Django 4.0.1 on 2022-02-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0020_student_profile_major_unitdata_unitguide_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorsequence',
            name='units',
        ),
        migrations.AddField(
            model_name='majorsequence',
            name='unit_set_code',
            field=models.CharField(blank=True, help_text='The code of the unit set', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='minorsequence',
            name='unit_set_code',
            field=models.CharField(blank=True, help_text='The code of the unit set', max_length=20, null=True),
        ),
    ]
