# Generated by Django 4.0.1 on 2022-02-13 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0022_remove_unitdata_trimester_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='active_semester',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='past',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unitdata',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
