# Generated by Django 4.0.1 on 2022-02-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0027_rename_weighting_assignment_weighting_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assessment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
