# Generated by Django 4.0.1 on 2022-02-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0028_assignment_assessment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assessment_type',
            new_name='task_type',
        ),
    ]
