# Generated by Django 4.0.1 on 2022-02-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0029_rename_assessment_type_assignment_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('GRADED', 'Graded'), ('DID_NOT_SUBMIT', "Didn't Submit")], default='NOT_STARTED', max_length=15, null=True),
        ),
    ]
