# Generated by Django 4.0.1 on 2022-02-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uniplan', '0030_alter_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='user_googledoc_url',
            field=models.URLField(blank=True, help_text='Your google doc link to the assignment', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user_notion_url',
            field=models.URLField(blank=True, help_text='Your notion url to the assignment', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('GRADED', 'Graded'), ('DID_NOT_SUBMIT', "Didn't Submit")], default='NOT_STARTED', max_length=20, null=True),
        ),
    ]
